name: Auto-merge build

on:
  workflow_dispatch:
    inputs:
      pr-number:
        type: string
  issue_comment:
    types:
      - created

run-name: ${{ (github.event.comment.user.id == 45397632 && github.event.issue.pull_request != null && (github.event.issue.user.id == 12746779 || github.event.issue.user.id == 41898282) && contains(github.event.comment.body, 'flatpak install') || inputs.pr-number) && format('Auto-merge PR {0}', github.event.issue.number || inputs.pr-number) || 'Skip auto-merge' }}

jobs:
  merge:
    if: (github.event.comment.user.id == 45397632 && github.event.issue.pull_request != null && (github.event.issue.user.id == 12746779 || github.event.issue.user.id == 41898282) && contains(github.event.comment.body, 'flatpak install')) || inputs.pr-number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Merge once the Flathub build has succeeded
        run: gh pr merge --squash ${{ github.event.issue.number || inputs.pr-number }}
        env:
          GH_TOKEN: ${{ github.token }}
